DROP TABLE IF EXISTS series CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS season CASCADE;
DROP TABLE IF EXISTS episodes CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS users_series;
DROP TABLE IF EXISTS series_genres;